# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Shannon Holloway"                                # Your name
  description: "Shannon is a human-centered product innovator"   # A brief slogan (optional)
  image: img/Shannon-facilitating-group-postits-square.jpg
  
  favicon: img/SLH-favicon.png
  google-analytics: "G-K50ZLQV0CG"
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: false
  
  # your sub-pages
    left:
      - text: "Resume"
        href: cv/index.qmd
        
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:info@shannonholloway.com"  
  

# Don't touch unless you know what you are doing :) ------------
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Shannon Holloway </span>
    right: |
      <span class="faux-block">Built with <a href="https://quarto.org/">Quarto</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true